### PR TITLE
Fix #177: spacing in toolbar

### LINKED ISSUE #177: No space between left margin and title in action bar
#### Software and hardware versions 
Moto G5 Plus, Android 9

#### Problem description
There is no space between title name and left margin in action bar

#### Steps to reproduce the problem
Open any screen and notice the action bar

#### Expected behavior
Space between the title and left margin in all of the screens

#### Other information 
Screenshot:
image

### PR DESCRIPTION
**Pull request by naman653**
Closes #177

### CODE REVIEW

**Comment by naman653** [comment]
@shobhitagarwal1612 Please review

**Comment by lakshyagupta21** [comment]
@naman653 Please claim the issue first, and always fill the PR template. It makes the review process faster.

**Comment by Chromicle** [comment]
Initially, I asked to work on this issue know @lakshyagupta21.

**Comment by lakshyagupta21** [comment]
@Chromicle This issue is marked as `good first issue` and I think you've done few in that category so you must be comfortable with code flow, my main motive is to assign `good first issue` to begineer so that they can setup the code enviornment and can start with some minor code fixes. Hope you understand.

**Comment by Chromicle** [comment]
Yeah ok then I search for another bugs

**Comment by naman653** [comment]
Sure @lakshyagupta21 , I'll remember that.

**Comment by shobhitagarwal1612** [comment]
Let's hold onto this one until #171 is merged. We should only merge if it doesn't look right even after that fix

**Comment by naman653** [comment]
Yes sure.

**Pull request merged**
