### PR TITLE
Added icons to all forms and settings

### LINKED ISSUE #212: Add Icons to forms and settings
#### Feature description
Currently, there are no icons to forms and settings so by adding the icons ideally also communicate the core essence of the feature

#### Steps to reproduce the problem
Not a problem new feature

#### Expected behavior
Good icons with vectors drawable resource files, the icon should match with feature and icon

#### Other things
while making the icons make the "Storage Location"  add the new text view and add ODK destination directory to in it

### PR DESCRIPTION
**Pull request by Chromicle**
Closes #212 
#### What has been done to verify that this works as intended?
Tested on my phone it is working fine as expected

#### GIF
icons

#### Why is this the best possible solution? Were any other approaches considered?
for each icon added the drawable files and then attached to each particular thing

#### How does this change affect users? 
 by adding the icons ideally also communicate the core essence of the feature so it will give the good user experience

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew check code` and confirmed all checks still pass OR confirm CircleCI build passes
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/share/blob/master/share_app/src/main/assets/open_source_licenses.html).

### CODE REVIEW

**Comment by shobhitagarwal1612** [comment]
+1 for the icons in the settings screen

For the forms icon, have a look at the latest release of ODK Collect. It's UI/UX was recently updated and this project should use the same iconography since the forms are shared between both

**Comment by Chromicle** [comment]
Did I add the blue icon only or else will I change the color to black

**Comment by shobhitagarwal1612** [comment]
> Did I add the blue icon only or else will I change the color to black

Sorry but I didn't get your question. Can you please rephrase this?

**Comment by Chromicle** [comment]
There are 2 type of icons are there for filled forms and blank forms know, did I make same colour or not

**Comment by Chromicle** [comment]
@shobhitagarwal1612 I updated according to odk collect I updated the PR template have a look once

**Comment by lakshyagupta21** [comment]
@Chromicle It looks like that there is no left margin added for the forms icon.

**Comment by Chromicle** [comment]
> @Chromicle Also if you've used the icons XML from any open source project then please mention in an open_source_licenses file (If it's not there);

Yeah I specified now

**Comment by Chromicle** [comment]
@shobhitagarwal1612 please review now I made some changes

**Comment by shobhitagarwal1612** [comment]
Thanks for this addition @Chromicle!

**Pull request merged**
