### PR TITLE
Support form receiving in Android 9

### LINKED ISSUE #154: Unable to receive blank forms in Android 9 devices
#### Software and hardware versions 
Android v9, Moto G5 Plus

#### Problem description
Unable to receive forms in Android 9 due to a known bug.
https://stackoverflow.com/questions/53005755/how-to-get-wifi-ssid-in-android-9-0pie
I ensured that location services were enabled and the permissions were given but still it doesn't work

#### Steps to reproduce the problem
Try to receive any blank form on Android 9 device

#### Expected behavior
Should work as expected

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Closes #154 

#### What has been done to verify that this works as intended?
Successfully transferred 10 blank forms from Nexus 5 (Android 6) to Moto G5 Plus(Android 9) multiple times

#### Why is this the best possible solution? Were any other approaches considered?
Earlier, we were relying on extra info for comparing the SSID. In this approach, I query for the SSID using the known list of wifi networks and current active wifi network. So, removing the dependency over any other information.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This might affect wifi connectivity. So must be properly tested

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew pmd checkstyle lint findbugs` and confirmed all checks still pass OR confirm CircleCI build passes
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/share/blob/master/share_app/src/main/assets/open_source_licenses.html).

### CODE REVIEW

**Comment by shobhitagarwal1612** [comment]
@lakshyagupta21 Please review

**Comment by lakshyagupta21** [comment]
@shobhitagarwal1612 Changes looks good to me, but I don't have Android 9 device to test.

**Comment by shobhitagarwal1612** [comment]
But it does work on your other devices, right? If so, then let's merge this PR and keep in mind to get this verified and documented by someone else in future.

**Comment by shobhitagarwal1612** [comment]
@lakshyagupta21 I have an Android 9 device for a couple more weeks. I am intending to add support for the sending mechanism as well before I have to give it back. Could you please review/merge this?

**Comment by lakshyagupta21** [comment]
@shobhitagarwal1612 Sorry for the delay will review it at the earliest.

**Comment by lakshyagupta21** [comment]
@shobhitagarwal1612 I'm trying to receive the forms in Android 9, but in its not showing sender's network and also if I'm trying to connect via 'SCAN QR Code' its not connecting it says No wifi network available. And I've tried on lower devices from Android 4.4 to 7.1 and vice versa its working fine.

**Comment by shobhitagarwal1612** [comment]
Thanks for testing it out. I'll try to get to the bottom of the problem you have faced.

**Comment by shobhitagarwal1612** [comment]
I tested in again and it works.
Sender Lenovo Tab (Android 6)
Receiver Moto G5 Plus (Android 9)

device_9

**Comment by shobhitagarwal1612** [comment]
>  showing sender's network 

Was the network visible on other devices or just this device?

**Comment by lakshyagupta21** [comment]
yes it was visible on other devices,  maybe its a device specific issue. I'll try to take a look into the issue.

**Comment by lakshyagupta21** [comment]
@shobhitagarwal1612 I'tried again after removing both the apps and their directories in both the devices, now it seems to be working.

**Comment by lakshyagupta21** [comment]
@shobhitagarwal1612 Thanks for adding support for Android 9.

**Pull request merged**
