### PR TITLE
Add Ability to Configure ODK Destination Dir

### LINKED ISSUE #105: Configurable ODK submissions destination folder
The ODK submissions destination folder is not configurable, can we make it configurable?

 A user may not always want the submission instances in the same folder, for example, to differentiate submissions from different devices when synchronised. Having the user set the destination folder would allow them to be able to delete data from other devices. This stems from our use case, where:
1. A group of enumerators in the field collect data
2. After every X enumerations, they meet, synchronise their submissions using ODK share
3. A separate tool checks coverage based on indicators in all submissions including synchronised submissions of the enumerators in the field (Note: data may not have been submitted to an ODK aggregate server yet, they could still be in the field with no internet access.)
4. At the end of the day, each enumerator only submits the data they collected to ODK Aggregate server.

1 - 3 only happens while enumerators are in the field, and they may be offline still and may not have submitted their data to an aggregate server.

### PR DESCRIPTION
**Pull request by rkodev**
Add the ability to change which directory files from other devices are
downloaded to.

Fixes  #105 

Signed-off-by: Jason Rogena
Signed-off-by: Ronald Kudoyi

### CODE REVIEW

**Comment by shobhitagarwal1612** [comment]
@rkodev Did you face the above mentioned problem on your device?

**Comment by rkodev** [comment]
@shobhitagarwal1612 yes, but I believe this issue has already been reported and worked in here #100

**Comment by shobhitagarwal1612** [comment]
> If I send a blank form and use a different destination folder, then in ODK Collect the form gets loaded properly but the media isn't as it still tries to look for the media in sdcard/odk/ folder

This bug is in ODK Collect side and is still present. Did you try to open the transferred instance after pushing to a different directory?

**Comment by shobhitagarwal1612** [comment]
Please resolve the conflicts. This PR can be merged then

**Comment by shobhitagarwal1612** [comment]
I have resolved the conflicts here https://github.com/opendatakit/skunkworks-crow/pull/190

Closing this

**Comment by shobhitagarwal1612** [comment]
The PR has been merged. Thanks for helping to improve the project!!!

**Pull request closed without merging**
