### PR TITLE
Update target version to 26

### LINKED ISSUE #119: TargeSdkVersion should be 26 or higher
Currently, the targetSdkVersion is 22 which is no longer supported.

Here's the lint error.

screenshot_2

* I think we should update it to 28.
* After updating it to 28, we will also have to update the compileSdkVersion to 28 as well.
@lakshyagupta21 @shobhitagarwal1612 What you think?

### PR DESCRIPTION
**Pull request by jddeep**
Closes #119 

#### What has been done to verify that this works as intended?
The whole gradle file has been updated as required.

#### Why is this the best possible solution? Were any other approaches considered?
Yes this is the best possible solution.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew pmd checkstyle lint findbugs` and confirmed all checks still pass OR confirm CircleCI build passes
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/share/blob/master/share_app/src/main/assets/open_source_licenses.html).

### CODE REVIEW

**Comment by jddeep** [comment]
@shobhitagarwal1612 please review.

**Comment by shobhitagarwal1612** [comment]
Did you try to send a form? I believe that you'd have to add runtime permissions as well along with updating the targetSdkVersion.

**Comment by jddeep** [comment]
@shobhitagarwal1612 what permissions do you think we should add in the Manifest? I have added some but want to confirm as you are involved in the project for a long time. By far I have not experienced any crash.

**Comment by jddeep** [comment]
@shobhitagarwal1612 while running the app crashes at the start. I get these errors on the console : `      Caused by: java.lang.RuntimeException: Cannot create directory: /storage/emulated/0/share
        at org.odk.share.application.Share.createODKDirs(Share.java:80)
        at org.odk.share.activities.MainActivity.onCreate(MainActivity.java:69) `

**Comment by jddeep** [comment]
I think writing to SD card is not supported by default on Android 6 and above. What do you say? @shobhitagarwal1612

**Comment by shobhitagarwal1612** [comment]
It's crashing because the permission to read and write is missing. So that needs to be asked on runtime

**Comment by jddeep** [comment]
The read and write external storage permssions are present in the Manifest file. But do I need to request self permission before ` super.onCreate() ` in MainActivity.java. @shobhitagarwal1612

**Comment by shobhitagarwal1612** [comment]
Have a look at this blog https://developer.android.com/distribute/best-practices/develop/runtime-permissions

**Comment by jddeep** [comment]
@shobhitagarwal1612 Yes I know. I was asking at which position to call the request permission method?

**Comment by shobhitagarwal1612** [comment]
I'd say that ideally, the permission needs to be requested before any read/write operation happens. So you need to identify where read/write operations are happening and ensure that the permission is always available before attempting to read/write.

**Comment by shobhitagarwal1612** [comment]
@jddeep Did you get a lead on how to add the runtime permission and the place where to add it?

**Comment by jddeep** [comment]
@shobhitagarwal1612 It will take a long time for me to find all the instances where the permssions are required as I am new to the project. Can you help me with some instances as you are involved in the project for a long time.

**Comment by shobhitagarwal1612** [comment]
> @shobhitagarwal1612 It will take a long time for me to find all the instances where the permssions are required as I am new to the project. Can you help me with some instances as you are involved in the project for a long time.

I understand that this is not an easy issue to fix as a first PR.  Did you at least give it a try? If you are not comfortable with this issue, you can always unclaim this one and pick an easier one.

**Comment by shobhitagarwal1612** [comment]
@jddeep Are you still working on the issue?

**Comment by shobhitagarwal1612** [comment]
@jddeep Sorry for closing this PR but there are other issues which depend on this. We have waited for more than 10 days but you still haven't updated the issue yet. Kindly pick another issue if you wish to work on the project

**Pull request closed without merging**
