### PR TITLE
[WIP] added the bluetooth utilities.

### LINKED ISSUE #253: [Feature] Add the bluetooth development framework
#### Problem description
We are going to build bluetooth methods. Should we using the native bluetooth server/client in Android SDK or using other open source wrapped bluetooth lib? 

A suggestion is [FastBle](https://github.com/Jasonchenlijian/FastBle), which uses simple ways to filter, scan, connect, read ,write, notify, readRssi, setMTU, and multiConnection using bluetooth. I was a user of this library and it works very good in my other applications. 

#### Expected behavior
Build native bluetooth server/client utils or adding a third-party bluetooth library.

#### Other information 
@opendatakit-bot claim

### PR DESCRIPTION
**Pull request by huangyz0918**
Closes #253 

#### What has been done to verify that this works as intended?
I have used this framework for a long time, this is a reliable Bluetooth development framework, very suitable for use in our projects. It's safe and fully tested.

Link to this lib: [FastBle](https://github.com/Jasonchenlijian/FastBle).

#### Why is this the best possible solution? Were any other approaches considered?
N/A

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
N/A

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkCode` and confirmed all checks still pass OR confirm CircleCI build passes
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/share/blob/master/share_app/src/main/assets/open_source_licenses.html).

### CODE REVIEW

**Comment by lakshyagupta21** [comment]
@huangyz0918 I assume that this library is useful for only BLE capable devices and in my knowledge, not all devices are BLE capable (correct me if I'm wrong), so how we're going to solve all of our app users problem using this library.

**Comment by huangyz0918** [comment]
Yes, BLE can only works in devices with Android 4.3 above. Should we use classic bluetooth method for all devices or using BLE for Android version > 4.3 and others using classic bluetooth? What do you think? @lakshyagupta21

**Comment by lakshyagupta21** [comment]
@huangyz0918 I'm not sure whether all devices greater than 4.3 support BLE or not.   And there are few limitations of BLE as well. 
Please go through this once https://www.thedroidsonroids.com/blog/bluetooth-classic-vs-bluetooth-low-energy-on-android-hints-implementation-steps

**Comment by huangyz0918** [comment]
@lakshyagupta21 You are right. To be on the safe side, I decided not to use Bluetooth BLE in this project. We still use the native android BluetoothAdapter. I will create the relevant bluetooth tools in this week first.

**Comment by lakshyagupta21** [comment]
Lets close this PR, you can raise another one whenever you're done with the changes for bluetooth.

**Pull request closed without merging**
