### PR TITLE
Fixes #157 Empty Dialog if blank form already available

### LINKED ISSUE #157: Empty transfer dialog if blank form already available
#### Software and hardware versions 
Android vx.x.x, device used...

#### Problem description
When transferring blank forms if all are already available at the receiver, then the resulting dialog is blank

#### Steps to reproduce the problem
Send blank forms which are already available in the receiver

#### Expected behavior
Result dialog should display that `Forms are already available` or something similar to indicate what has happened.

Screenshot:
image

### PR DESCRIPTION
**Pull request by rohap97**
Closes #157 

#### Why is this the best possible solution? Were any other approaches considered?
This is possibly the best solution.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Empty dialog gets fixed/

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew pmd checkstyle lint findbugs` and confirmed all checks still pass OR confirm CircleCI build passes
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/share/blob/master/share_app/src/main/assets/open_source_licenses.html).

### CODE REVIEW

**Comment by shobhitagarwal1612** [comment]
@rohap97 Does it fix the issue at the receiver end or the sender end? Also, please mention the steps you had to take to verify that the issue is fixed by this change

**Comment by rohap97** [comment]
@shobhitagarwal1612 This resolves the issue on the Sender end. The steps that I took to verify it include:-

Step 1. Sent a  form to other device.
Step 2. Tried sending same form to the other device.
Step 3. Received this dialog box.

screenshot_2019-03-09-01-27-38-465

**Comment by lakshyagupta21** [comment]
The changes look good to me, please resolve the conflicts.

**Comment by shobhitagarwal1612** [comment]
@rohap97 thanks for your patience and for working on this. This issue happens on the receiver end as well. So that needs to be handled too

**Comment by rohap97** [comment]
@iadeelzafar When trying to resolve conflicts in this PR, I followed your steps till `git rebase master`. And then I switched to Android Studio. But there were no conflicting lines anywhere. What could have gone wrong according to you?

**Comment by iadeelzafar** [comment]
@rohap97 There must be conflicts. Sometimes the conflicts are just space lines.
Look into these files
Conflicting files
``` share_app/src/main/java/org/odk/share/tasks/UploadJob.java ```
``` share_app/src/main/res/values/strings.xml ```

**Comment by shobhitagarwal1612** [comment]
> I followed your steps till git rebase master. And then I switched to Android Studio. But there were no conflicting lines anywhere. What could have gone wrong according to you?

This is because you rebased onto your forked repo's `master` branch instead of the project's `master` branch

To do this, 

` git remote add upstream https://github.com/opendatakit/skunkworks-crow `
`git fetch upstream master`
`git rebase upstream/master`

**Comment by rohap97** [comment]
@shobhitagarwal1612 Sir, I followed your instructions and was able to solve Merge conflicts. Thank you very much sir!

**Comment by shobhitagarwal1612** [comment]
> This issue happens on the receiver end as well. So that needs to be handled too

@rohap97 this is still not resolved

**Comment by lakshyagupta21** [comment]
@rohap97 Can you please fix the merge conflicts?

**Comment by shobhitagarwal1612** [comment]
Closing the PR. Please reopen if you wish to continue working on it

**Pull request closed without merging**
