### PR TITLE
Updated dagger version

### LINKED ISSUE #158: Upgrade dagger dependency
#### Problem description
We use [dagger](https://github.com/google/dagger) for injecting dependencies. The current version is 2.16. 
A new version of dagger 2 is also available (2.19).

### PR DESCRIPTION
**Pull request by iamvasuh**
Closes #158

What has been done to verify that this works as intended?

when I did the commit and ran the gradle sync in the android studio, it's not showing any error and also builds successfully thus verifying that it works as intended.

Why is this the best possible solution? Were any other approaches considered?

Yes,this is the best possible solution.

How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

As the dagger version is updated from 2.16 to 2.19 , users will get to use the latest versoin of the respective dagger-2 library.

Before submitting this PR, please make sure you have:
- [ ] run `./gradlew pmd checkstyle lint findbugs` and confirmed all checks still pass OR confirm CircleCI build passes
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/share/blob/master/share_app/src/main/assets/open_source_licenses.html).

### CODE REVIEW

**Comment by iamvasuh** [comment]
transfer result
it's working fine

**Comment by lakshyagupta21** [comment]
Don't raise different PRs if anything goes wrong with your old PRs. If you have any doubts related to Git then please ask this is how we learn by committing mistakes.

**Comment by lakshyagupta21** [comment]
Lets close this we'll work on the previous one.

**Comment by iamvasuh** [comment]
> Don't raise different PRs if anything goes wrong with your old PRs. If you have any doubts related to Git then please ask this is how we learn by committing mistakes.

I had been doing it from the Android studio itself....it got a bit messed up so I thought of making a new one and deleting the previously forked repo.

**Comment by lakshyagupta21** [comment]
Okay, its fine but this is just a one file change so it has not created that much problem but when  we work on different branches at single time then doing this would create lot of problems.  So  if you get stuck somewhere on any issue ask on the channel someone will definitely respond and resolve your queries.
And one thing that I noticed is that you raise all your PRs from your master branch,  which should not happen because we keep our master so that we can update it with upstream master.  We never work on master you have create swperate branch from master lets say `task-abcd` then work on that branch.

**Comment by iamvasuh** [comment]
> Okay, its fine but this is just a one file change so it has not created that much problem but when we work on different branches at single time then doing this would create lot of problems. So if you get stuck somewhere on any issue ask on the channel someone will definitely respond and resolve your queries.
> And one thing that I noticed is that you raise all your PRs from your master branch, which should not happen because we keep our master so that we can update it with upstream master. We never work on master you have to create separate branch from master lets say `task-abcd` then work on that branch.

I will surely keep these suggestions in mind and won't do inaccurate ways of opening a PR

**Comment by lakshyagupta21** [comment]
Now you've again closed a PR. Three PR for the same issue.

**Pull request closed without merging**
