### PR TITLE
Fix #146 Added progress bar in wifi activity

### LINKED ISSUE #146: Addition of progress bar while scanning for wifi.
#### Problem description
When clicking on Scan Wifi button on Connect to Wifi screen, it shows a simple TextView containing text "Scanning. Please wait". My idea is to include a progressBar or progressDialog for this to enhance the user experience.

#### Steps to reproduce the problem
Make sure you have Wifi enabled.
Click on Receive button.
Click on Scan Wifi button.

A simple text will be shown "Scanning. Please wait"
#### Expected behavior
A nice progressBar or progressDialog can be shown for improving User experience.

### PR DESCRIPTION
**Pull request by naman653**
Closes #146

#### What has been done to verify that this works as intended?
I've added the progress bar so as to provide better UI/UX.

#### Why is this the best possible solution? Were any other approaches considered?
I've considered the case to change visibility of progress bar accordingly while scanning or not.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This change provides better UI so that the user can know something is being done in background.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkCode` and confirmed all checks still pass OR confirm CircleCI build passes
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/share/blob/master/share_app/src/main/assets/open_source_licenses.html).

### CODE REVIEW

**Comment by naman653** [comment]
@lakshyagupta21 @shobhitagarwal1612 Please review.

**Comment by Chromicle** [comment]
@naman653 Please do not remove the default template as it is there for a particular reason. It helps the code reviewers and other contributors as well.
so further if we want we can understand easily. 
you will find PR [template](https://github.com/opendatakit/skunkworks-crow/blob/master/.github/PULL_REQUEST_TEMPLATE.mdl) here

**Comment by lakshyagupta21** [comment]
@naman653  Can you fix the review comments as well as fix the merge conflicts, then I think its good to go.

**Comment by shobhitagarwal1612** [comment]
Let's wait for a couple more days. Then maybe you can finalize this PR and merge

**Comment by naman653** [comment]
Sorry busy due to festival, Will resolve this by today

**Comment by shobhitagarwal1612** [comment]
@naman653 Thanks for fixing this! :tada: :tada: :tada:

**Pull request merged**
