### PR TITLE
Fixes Issue#352: No adapter attached; Skipping layout in BlankFormsFragment and FilledFormsFragment

### LINKED ISSUE #352: No adapter attached; Skipping layout in BlankFormsFragment and FilledFormsFragment
#### Software and hardware versions 
Android vx.x.x, device used...
Android 9, Vivo V11 Pro

#### Problem description
Calling the `setAdapter` method in `onLoadFinished` , i.e. a delayed method, leads to the error 
`E/RecyclerView: No adapter attached; skipping layout`. 

#### Steps to reproduce the problem
1. Open the app
2. Click on the `Send` button.
3. In Android Logcat, it shows the error: `E/RecyclerView: No adapter attached; skipping layout`

ogcat-skipping-layout-before

#### Expected behavior
The layout gets attached on the start of the loader and thus, no such error is shown in the logcat.

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

### PR DESCRIPTION
**Pull request by SaumiaSinghal**
Closes #352 

#### What has been done to verify that this works as intended?
I tested it on Android 9.0.

**Android Studio Logcat on new branch:**
logcat-skipping-layout-debug

**Android Studio Logcat on master branch:**
ogcat-skipping-layout-before

#### Why is this the best possible solution? Were any other approaches considered?
I found that the `instanceAdapter` and `formAdapter` was getting attached in the `onLoadFinished` method, which is sometimes delayed. I followed the documentation at Android developers, [here](https://developer.android.com/guide/components/loaders), and found that it is better to attach the adapter in the `onCreateLoader` method, and update the cursor, later on, in `onLoadFinished` method. 

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
I don't think there are any regression risks, as of now. 

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkCode` and confirmed all checks still pass OR confirm CircleCI build passes
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/share/blob/master/share_app/src/main/assets/open_source_licenses.html).

### CODE REVIEW

**Comment by huangyz0918** [comment]
Please resolve conflicts @SaumiaSinghal , thanks.

**Comment by huangyz0918** [comment]
Hi @SaumiaSinghal , thanks so much for this fix, has the issue mentioned [here](https://github.com/opendatakit/skunkworks-crow/issues/352#issuecomment-581565173) been solved by your fix? Have you test about that in Android 9?

> on my device, Android 9, it leads to a crash sometime and fails to populate the view in the mentioned fragments

I believe some crashes may be introduced by the UI but I'm not sure.

**Comment by SaumiaSinghal** [comment]
Hie @huangyz0918! Thanks for reviewing. Yes, this fix solved the issue for me. I no longer see the error message `No adapter attached; Skipping layout` in the log.

**Comment by huangyz0918** [comment]
Thanks @SaumiaSinghal, the changes worked well in my devices.

**Pull request merged**
